import { Provider} from 'react-redux'
import store from '@component/store/store'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Emeklilik Hesaplama Programı",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <body >
        <Provider store= {store}>
        {children}
        </Provider>
          </body>

      </html>
   
  );
}